# Generated by Django 5.1.5 on 2025-01-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('matric_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('computer_science', 'Computer Science'), ('computer_engineering', 'Computer Engineering'), ('civil_engineering', 'Civil Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('chemical_engineering', 'Chemical Engineering'), ('science_laboratory', 'Science Laboratory Technology'), ('food_technology', 'Food Technology'), ('accountancy', 'Accountancy'), ('business_admin', 'Business Administration'), ('marketing', 'Marketing'), ('mass_comm', 'Mass Communication')], max_length=50)),
                ('level', models.CharField(choices=[('nd1', 'ND 1'), ('nd2', 'ND 2'), ('hnd1', 'HND 1'), ('hnd2', 'HND 2')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=179)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='textbooks/')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.textbook')),
            ],
        ),
    ]
