# Generated by Django 5.1.5 on 2025-01-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
